django-prosoul/django_prosoul/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView


urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/prosoul')),
    url(r'^admin/', admin.site.urls, name="admin"),
    url(r'^accounts/login/$', auth_views.LoginView.as_view()),
    url('^', include('django.contrib.auth.urls')),
    url(r'^prosoul/', include('prosoul.urls', namespace='prosoul'))
]

urlpatterns += [url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))]

django-prosoul/prosoul/urls.py
# -*- coding: utf-8 -*-
#
# Copyright (C) 2015-2020 Bitergia
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Authors:
#   Alvaro del Castillo San Felix <acs@bitergia.com>
#   David Moreno <dmoreno@bitergia.com>
#
#

from django.conf.urls import include, url
from django.views.generic import RedirectView

from rest_framework import routers

from . import views
from prosoul.views_editor import AttributeView, EditorView, GoalView, MetricView, MetricDataView, QualityModelView
from prosoul.views_editor import import_from_file, export_to_file

from prosoul.rest import AttributeViewSet, DataSourceTypeViewSet, FactoidViewSet, GoalViewSet
from prosoul.rest import MetricViewSet, MetricDataViewSet, QualityModelViewSet, UserViewSet

app_name = 'prosoul'

urlpatterns_edit = [
    url(r'^editor$', EditorView.as_view(), name='editor'),
    url(r'^import$', import_from_file),
    url(r'^export/qmodel=(?P<qmodel>[\w ]+)', export_to_file),
    url(r'^export$', export_to_file),
    url(r'^add_qmodel$', QualityModelView.as_view(action=QualityModelView.add_qmodel)),
    url(r'^remove_qmodel$', QualityModelView.as_view(action=QualityModelView.remove_qmodel)),
    url(r'^select_qmodel$', QualityModelView.as_view(action=QualityModelView.select_qmodel)),
    url(r'^update_qmodel$', QualityModelView.as_view(action=QualityModelView.update_qmodel)),
    url(r'^add_goal$', GoalView.as_view(action=GoalView.add_goal)),
    url(r'^remove_goal$', GoalView.as_view(action=GoalView.remove_goal)),
    url(r'^select_goal$', GoalView.as_view(action=GoalView.select_goal)),
    url(r'^update_goal$', GoalView.as_view(action=GoalView.update_goal)),
    url(r'^add_attribute$', AttributeView.as_view(action=AttributeView.add_attribute)),
    url(r'^remove_attribute$', AttributeView.as_view(action=AttributeView.remove_attribute)),
    url(r'^select_attribute$', AttributeView.as_view(action=AttributeView.select_attribute)),
    url(r'^update_attribute$', AttributeView.as_view(action=AttributeView.update_attribute)),
    url(r'^add_metric$', MetricView.as_view(action=MetricView.add_metric)),
    url(r'^remove_metric$', MetricView.as_view(action=MetricView.remove_metric)),
    url(r'^select_metric$', MetricView.as_view(action=MetricView.select_metric)),
    url(r'^update_metric$', MetricView.as_view(action=MetricView.update_metric)),
    url(r'^add_metric_data$', MetricDataView.as_view(action=MetricDataView.add_metric_data))
]

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='viewer')),
    url(r'^viewer$', views.Viewer.as_view(), name='viewer'),
    url(r'^visualize$', views.Visualize.as_view(), name='viz'),
    url(r'^create_visualization$', views.Visualize.as_view()),
    url(r'^assess$', views.Assessment.as_view(), name='assess'),
    url(r'^create_assessment$', views.Assessment.as_view()),
    url(r'^download_assessment_csv', views.download_csv),
    url(r'^download_project_assessment_csv/(?P<project>[\w ]+)', views.download_csv)
]

urlpatterns += urlpatterns_edit

#############
# REST routes support

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'attributes', AttributeViewSet)
router.register(r'factoid', FactoidViewSet)
router.register(r'goal', GoalViewSet)
router.register(r'datasourcetype', DataSourceTypeViewSet)
router.register(r'metric', MetricViewSet)
router.register(r'metricdata', MetricDataViewSet)
router.register(r'qualitymodels', QualityModelViewSet)
router.register(r'users', UserViewSet)
#############

urlpatterns += [url(r'^api/', include(router.urls))]

django-prosoul/django_prosoul/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block head %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Prosoul {% block title %}{% endblock %}</title>
        <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
        <script
            src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha256-k2WSCIexGzOj3Euiig+TlR8gA0EmPjuc79OEeY5L45g="
            crossorigin="anonymous"></script>
        <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.min.js" integrity="sha256-TueWqYu0G+lYIimeIcMI8x1m14QH/DQVt4s9m/uuhPw=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.10/js/select2.min.js" integrity="sha256-d/edyIFneUo3SvmaFnf96hRcVBcyaOy96iMkPez1kaU=" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.10/css/select2.min.css" integrity="sha256-FdatTf20PQr/rWg+cAKfl6j4/IY3oohFAJ7gVC3M34E=" crossorigin="anonymous" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/css/bootstrap-datepicker.min.css" integrity="sha256-I4gvabvvRivuPAYFqevVhZl88+vNf2NksupoBxMQi04=" crossorigin="anonymous"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        {% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a href="/" class="navbar-brand">Prosoul</a>

            <ul class="navbar-nav">
              <li class="nav-item">
                  <a class="nav-link {% if active_page == 'viewer' %} active {% endif %}" href="{% url 'prosoul:viewer' %}">View</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link {% if active_page == 'editor' %} active {% endif %}" href="{% url 'prosoul:editor' %}">Edit</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link {% if active_page == 'visualize' %} active {% endif %}" href="{% url 'prosoul:viz' %}">Visualize</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link {% if active_page == 'assess' %} active {% endif %}" href="{% url 'prosoul:assess' %}">Assess</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link {% if active_page == 'admin' %} active {% endif %}" href="{% url 'admin:index' %}">Admin (admin/admin for login)</a>
              </li>
            </ul>
            {% if user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a href="{% url 'logout' %}?next={% url 'prosoul:viewer' %}" class="navbar-text" style="display: right">Logout</a>
                </li>
            </ul>
            {% endif %}

        </nav>
        <div class="container-fluid">
            {% if err != None %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                <strong>Ooos!</strong> {{err}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endif %}
        {% block body %}{% endblock %}
        </div>
        <footer class="footer fixed-bottom container-fluid bg-4 text-center" style="margin-bottom: 20px;">
          Powered by <a href="https://grimoirelab.github.io">GrimoireLab</a>
        </footer>
    </body>
</html>